language: java
jdk:
  - oraclejdk8
  - oraclejdk9
install: false

script: mvn clean package -DskipTests=true

deploy:
  provider: releases
  api_key: $GITAPI
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
    - $HOME/.m2
