language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8

install: false

script: mvn clean package -DskipTests=true

deploy:
  provider: releases
  api_key: $GITAPI
  file: "target/coinbase-pro-client*.jar"
  skip_cleanup: true
  on:
    tags: true
